<a href="https://colab.research.google.com/github/Paresh-0007/DS_LAB_MP/blob/main/DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd


files = [
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-1-4.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-5-8.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-9-12.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-13-17.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-18-21.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-22-25.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-26-31.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-32-36.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-37-41.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-42-46.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-47-51.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-52-55.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-56-61.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-62-67.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-68-71.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-72-75.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-76-76.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-77-81.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-82-88.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-89-94.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-95-98.csv',
    '/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_mumbai_data-page-99-100.csv'
]

datalist = [pd.read_csv(file) for file in  files]
data = pd.concat(datalist,ignore_index=True)

In [ ]:
data.shape

(2527, 20)

In [ ]:
data.to_csv('/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats.csv', mode='a', header=True, index=False)

##Removing Nulls

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2527 entries, 0 to 2526
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2527 non-null   object
 1   society          2527 non-null   object
 2   link             2527 non-null   object
 3   price            2331 non-null   object
 4   area             2331 non-null   object
 5   areaWithType     2331 non-null   object
 6   bedRoom          2331 non-null   object
 7   bathroom         2331 non-null   object
 8   balcony          2331 non-null   object
 9   additionalRoom   1364 non-null   object
 10  address          2331 non-null   object
 11  floorNum         2331 non-null   object
 12  facing           2205 non-null   object
 13  agePossession    2330 non-null   object
 14  nearbyLocations  2316 non-null   object
 15  description      2331 non-null   object
 16  furnishDetails   998 non-null    object
 17  features         2307 non-null   object
 18  rating           2251 non-null   object
 19  property_id      2331 non-null   object
dtypes: object(20)
memory usage: 395.0+ KB

In [ ]:
data.dropna(subset=['price'],inplace=True)

In [ ]:
data.shape

(2331, 20)

In [ ]:
data.head()

,property_name,society,link,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"3 BHK Flat in Pant Nagar, Ghatkopar",72 park side,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.7 Crore,"₹ 36,815 per sq.ft.",Carpet area: 1005 (93.37 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,"Pooja Room,Study Room,Store Room","11111, Pant Nagar, Ghatkopar",7th of 21 Floors,North-East,0 to 1 Year Old,"['Siddhivinayak Temple', 'ganesh mandir', 'Khu...",This 3 bhk apartment is available for sale in ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",Q79229345
1,"2 BHK Flat in Anjurdive, Thane",Lodha Upper Thane,https://www.99acres.com/2-bhk-bedroom-apartmen...,59 Lac,"₹ 11,132 per sq.ft.",Carpet area: 530 (49.24 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Anjurdive, Thane",16th of 20 Floors,South-East,1 to 5 Year Old,"['Viviana Mall', 'Supermarket', 'Sai Super Mar...",Lodha upper thane is one of thane outskirts's ...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management3.7 out of 5', 'Green Area4.2 out ...",B75231863
2,"2 BHK Flat in Veera Desai Road, Andheri West",Bhairav Co Op Hsg Society,https://www.99acres.com/2-bhk-bedroom-apartmen...,2 Crore,"₹ 26,666 per sq.ft.",Carpet area: 625 (58.06 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"505, B Wing, Veera Desai Road, Andheri West",5th of 7 Floors,North,10+ Year Old,"['Azad nagar metro station', 'D n nagar metro ...",Residential apartment\nThis is your chance to ...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",S79968421
3,"3 BHK Flat in Vile Parle East, Mumbai",Samkit Apartments,https://www.99acres.com/3-bhk-bedroom-apartmen...,5.33 Crore,"₹ 42,500 per sq.ft.",Carpet area: 1254.55 (116.55 sq.m.),3 Bedrooms,4 Bathrooms,No Balcony,Pooja Room,"Vile Parle East, Mumbai",4th of 6 Floors,East,0 to 1 Year Old,"['Jayashree', 'Church', 'Parle Jin Mandir', 'J...",Residential apartment\nThis is your chance to ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.4 out of 5', 'Connectivity4.5 out of...",S80233673
4,"3 BHK Flat in Worli, Mumbai",Lodha Adrina,https://www.99acres.com/3-bhk-bedroom-apartmen...,7.9 Crore,"₹ 69,542 per sq.ft.",Carpet area: 1136 (105.54 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,Servant Room,"Worli, Mumbai",53 of 68 Floors,NaN,Within 6 months,"['Lower Parel Station', 'Asalpha Metro Station...",Residential apartment\nThis is your chance to ...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.3 out of 5', 'Connectivity4.4 out of...",P78904727

In [ ]:
data.rename(columns={'area':'price_per_sqft'},inplace=True)

In [ ]:
data.head()

,property_name,society,link,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"3 BHK Flat in Pant Nagar, Ghatkopar",72 park side,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.7 Crore,"₹ 36,815 per sq.ft.",Carpet area: 1005 (93.37 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,"Pooja Room,Study Room,Store Room","11111, Pant Nagar, Ghatkopar",7th of 21 Floors,North-East,0 to 1 Year Old,"['Siddhivinayak Temple', 'ganesh mandir', 'Khu...",This 3 bhk apartment is available for sale in ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",Q79229345
1,"2 BHK Flat in Anjurdive, Thane",Lodha Upper Thane,https://www.99acres.com/2-bhk-bedroom-apartmen...,59 Lac,"₹ 11,132 per sq.ft.",Carpet area: 530 (49.24 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Anjurdive, Thane",16th of 20 Floors,South-East,1 to 5 Year Old,"['Viviana Mall', 'Supermarket', 'Sai Super Mar...",Lodha upper thane is one of thane outskirts's ...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management3.7 out of 5', 'Green Area4.2 out ...",B75231863
2,"2 BHK Flat in Veera Desai Road, Andheri West",Bhairav Co Op Hsg Society,https://www.99acres.com/2-bhk-bedroom-apartmen...,2 Crore,"₹ 26,666 per sq.ft.",Carpet area: 625 (58.06 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"505, B Wing, Veera Desai Road, Andheri West",5th of 7 Floors,North,10+ Year Old,"['Azad nagar metro station', 'D n nagar metro ...",Residential apartment\nThis is your chance to ...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",S79968421
3,"3 BHK Flat in Vile Parle East, Mumbai",Samkit Apartments,https://www.99acres.com/3-bhk-bedroom-apartmen...,5.33 Crore,"₹ 42,500 per sq.ft.",Carpet area: 1254.55 (116.55 sq.m.),3 Bedrooms,4 Bathrooms,No Balcony,Pooja Room,"Vile Parle East, Mumbai",4th of 6 Floors,East,0 to 1 Year Old,"['Jayashree', 'Church', 'Parle Jin Mandir', 'J...",Residential apartment\nThis is your chance to ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.4 out of 5', 'Connectivity4.5 out of...",S80233673
4,"3 BHK Flat in Worli, Mumbai",Lodha Adrina,https://www.99acres.com/3-bhk-bedroom-apartmen...,7.9 Crore,"₹ 69,542 per sq.ft.",Carpet area: 1136 (105.54 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,Servant Room,"Worli, Mumbai",53 of 68 Floors,NaN,Within 6 months,"['Lower Parel Station', 'Asalpha Metro Station...",Residential apartment\nThis is your chance to ...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.3 out of 5', 'Connectivity4.4 out of...",P78904727

In [ ]:
data['society'].value_counts()

society
Kanakia Silicon Valley       91
Lodha New Cuffe Parade       90
Atmosphere O2                37
The Dosti Eastern Bay        30
Sky City by Oberoi Realty    29
                             ..
Seema Rajdhani                1
krishna heights               1
New saket                     1
Anurag                        1
Eon One                       1
Name: count, Length: 922, dtype: int64

In [ ]:
data['society'] = data['society'].str.lower()

In [ ]:
data['society']

0                    72 park side
1               lodha upper thane
2       bhairav co op hsg society
3               samkit apartments
4                    lodha adrina
                  ...
2522                 runwal bliss
2523                 runwal bliss
2524                      eon one
2525        adani western heights
2526                  monte south
Name: society, Length: 2331, dtype: object

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
data['society'].value_counts()

society
kanakia silicon valley                            91
lodha new cuffe parade                            90
atmosphere o2                                     37
on request                                        35
the dosti eastern bay                             30
sky city by oberoi realty                         29
gurukrupa marina enclave                          26
l and t emerald isle                              26
godrej platinum                                   26
piramal aranya                                    25
white city                                        24
monte south                                       23
lodha raj infinia                                 21
dosti eastern bay                                 20
lodha the park                                    20
godrej nest                                       19
bm satyam solaris                                 18
omkar signet                                      18
godrej urban park                                 17
runwal bliss                                      17
l and t crescent bay                              16
nahars amrit shakti                               16
godrej tranquil                                   15
kalpataru radiance                                15
shapoorji pallonji vicinia                        14
godrej rks                                        14
peninsula salsette 27                             14
wadhwa boulevard                                  13
siddha seabrook                                   13
lokhandwala octacrest                             12
rustomjee summit                                  12
nahar yarrow yucca vinca                          11
shapoorji pallonji astron                         11
rustomjee crown                                   11
piramal mahalaxmi                                 10
imperial heights                                  10
bholenath hresa                                   10
romell orbis                                      10
oberoi splendor                                   10
bhoomi simana                                     10
kukreja chembur heights 2                         10
spring grove tower                                 9
naman habitat                                      9
tricity natraj                                     9
wadhwa promenade at the address                    9
kalpataru crest                                    9
rivali park                                        9
ajmera boulevard                                   9
abrol signature                                    8
ganga chs                                          8
lodha adrina                                       8
tridhaatu morya                                    8
elegant navratnamala chs                           8
dlh leo tower                                      8
lokhandwala whispering palms xxclusives            8
ranbir heights                                     8
godrej the trees                                   8
jyoti sukriti                                      7
lodha kiara                                        7
omkar alta monte                                   7
ashok odyssey                                      7
sindhi society                                     7
susharda edifice celestial                         7
hiranandani regent hill                            7
bhoomi park                                        7
godrej central                                     7
lake lucerne                                       7
rustomjee elanza                                   7
runwal elegante                                    6
oberoi esquire                                     6
rna ng eclat                                       6
uk iridium                                         6
wadhwa tw gardens                                  6
avirahi heights                                    6
lodha world towers                                 6
lodha evoq                                         6
sd siennaa                                         6
satellite tower chs                                6
72 parksyde                                        6
lodha vista                                        6
adonia apartments                                  6
db woods                                           5
sunteck signia high                                5
bajaj shubhada                                     5
building                                           5
diamond garden                                     5
lake primrose                                      5
rustomjee seasons                                  5
sangam the luxor                                   5
indiabulls sky forest                              5
oberoi woods                                       5
peninsula celestia spaces                          5
oberoi exquisite                                   5
shreeji towers                                     5
runwal forests                                     5
kukreja complex                                    5
mahindra lifespaces splendour                      5
hiranandani avalon                                 5
l and t veridian at emerald isle                   5
piramal revanta                                    5
eternia by oberoi realty                           5
raheja ascencio                                    5
the atmosphere                                     5
ap panchvati b                                     4
shree udyan                                        4
kolte patil verve                                  4
lodha fiorenza                                     4
kalpataru avana                                    4
green view chs                                     4
lokhandwala sapphire heights                       4
raheja willows                                     4
omkar alta monte and signet                        4
godrej horizon                                     4
godrej garden enclave                              4
nahar yvonne                                       4
naman premier                                      4
royal diamond park                                 4
rohan lifescapes  prithvii                         3
ekta meadows                                       3
mahindra vicino                                    3
lalani grandeur                                    3
lodha estrella                                     3
suraj the palette                                  3
advait skyline                                     3
scorpio by jasani realty                           3
yog aashray                                        3
adityaraj gateway                                  3
sheth irene                                        3
jvpd road                                          3
hubtown seasons                                    3
lotus sky gardens                                  3
k raheja vistas                                    3
acme oasis                                         3
lalani velentine apartment 1                       3
nahar lilium lantana                               3
akshar amar mansion                                3
lodha trump tower                                  3
sheth vasant pride                                 3
mount everest apartment                            3
tavisa                                             3
prescon midtown bay                                3
celestial                                          3
group seven rushi heights                          3
zynergy                                            3
lokhandwala riviera tower                          3
nahar tulipia and tilia apartment                  3
wadhwa vista                                       3
dosti oro 67                                       3
wadhwa dukes horizon                               3
godrej prime                                       3
dheeraj insignia                                   3
horizon sapphire                                   3
adityavardhan apartment                            3
harasiddh viraaj                                   3
kanakia silicon valley.                            3
ajmera bhakti park sector 1 and 2                  3
kanakia zen world                                  3
triumph towers                                     3
lodha aqua                                         3
nahar arum and amanda                              3
aditya hari smruti chs                             3
ten bkc                                            3
evershine crown                                    3
omkar 1973 worli                                   3
kalpataru woodsville                               3
fressia ranibello                                  3
oberoi springs                                     3
paradigm artteza                                   3
thapar suburbia                                    3
ap nutex                                           3
sethia imperial avenue                             2
trishabh greens                                    2
neelam solstice                                    2
elite vista                                        2
runwal symphony                                    2
lodha world view                                   2
arkade aspire                                      2
vaishno heights                                    2
pcpl sparsh                                        2
mauli omkar 2                                      2
union park                                         2
hiranandani torino                                 2
runwal serene                                      2
vasant smruti                                      2
vabhav laxmi cristal sapphire                      2
viceroy savana                                     2
cornerstone tower                                  2
ashish  apartment                                  2
haware ipsa                                        2
nahar jonquille and jamaica                        2
rizvi cedar                                        2
apsara heritage                                    2
kohinoor city phase 2                              2
10th road                                          2
palatial heights                                   2
raheja vistas                                      2
hiranandani heritage                               2
kalpataru vienta                                   2
ld viceroy                                         2
rizvi oak                                          2
ao f residences                                    2
rna oakland park                                   2
vaibhavlaxmi royal stone                           2
estella society ghatkopar                          2
shreenathji celestial heights                      2
chembur                                            2
sunset 2 chs                                       2
shri niketan                                       2
sunteck city avenue 2                              2
l&t emerald isle tower 2                           2
the residency by lak and hanware realty llp        2
nahar iris ivy                                     2
geecee proximus                                    2
chembur naka                                       2
bombay realty island city center                   2
velentine tower                                    2
mahindra vivante                                   2
dharti height                                      2
heritage solitaire                                 2
kalpataru aura                                     2
golden rays                                        2
arum                                               2
dosti acres                                        2
rising city                                        2
lodha eternis                                      2
orchid tower                                       2
hdil metropolis residences                         2
prestige jasdan classic                            2
mangal orchid                                      2
lalani velentine apartments                        2
sunteck city avenue 4                              2
peninsula ashok towers                             2
aayush ayaansh apartment                           2
sadguru complex                                    2
mahavir arham mourya                               2
srishti elegance                                   2
raheja solitaire                                   2
ap ekam                                            2
tridhaatu aranya                                   2
garden view                                        2
enigma by oberoi realty                            2
rashi tower                                        2
shraddha pinnacle                                  2
silicon park                                       2
hiranandani brentwood                              2
shree shivam chs                                   2
avighna                                            2
adani western heights                              2
hiranandani octavius                               2
ashar titan                                        2
vrindavan building                                 2
mittal phoenix towers                              2
the 25 south                                       2
almeida apartments                                 2
raiaskaran parthenon                               2
dg sheetal usha and nisha                          2
ruparel ariana                                     2
mount alps                                         2
lodha bel air                                      2
gulmohar road                                      2
neptune flying kite                                2
gurukrupa aagam                                    2
lokhandwala minerva                                2
silicon valley                                     2
mahimkar residency                                 2
kalpataru estate                                   2
nicco residency andheri east                       2
dosti acres aster                                  2
rubberwala white house                             2
shubham seychelles                                 2
one meraki                                         2
signia pearl                                       2
jivan prakash                                      2
nahar rosa alba                                    2
ivory towers chs                                   2
gemstar sonata                                     2
vaibhavlaxmi central park                          2
neelam senroofs                                    2
dharti pressidio                                   2
bajaj emerald                                      2
micl aaradhya one earth                            2
konark zen gardens                                 2
dhaval sunrise charkop                             2
nahar laurel and lilac                             2
ajit barve anand heights                           1
the sugee  atharva , prabhadevi                    1
dahanukarwadi milan chsl ltd                       1
mandhana manor                                     1
shanta durga                                       1
pranav neon heights                                1
amol chs                                           1
poppy chs                                          1
parshwanath                                        1
the shree udyan                                    1
avant hillway                                      1
n terrace                                          1
ashay chs                                          1
cosmic heights                                     1
safal saraswati chs                                1
kalpataru habitat                                  1
ng royal park                                      1
shree udyan ch                                     1
windermere chs                                     1
p paradise                                         1
omkar ananta                                       1
kyraa ariso apartment                              1
prime rose                                         1
umang heights                                      1
kinara chs                                         1
kinara tower                                       1
surya gokul panchavati                             1
shikara heights                                    1
kohinoor apartment                                 1
raj el prado                                       1
shree praful chs                                   1
riviera                                            1
wadhwa the address                                 1
navageeta chs                                      1
central avenue apartments                          1
dukes horizon                                      1
harshal devchhaya                                  1
umesh apartment dahisar east                       1
eden gardens                                       1
sunbeam                                            1
gokul blossom                                      1
dynamix avanya                                     1
gurukrupa vyom                                     1
valencia apartment                                 1
shraddharpan hum sub chsl                          1
bhatia esspee square                               1
shree  ganesh chs                                  1
kalpataru towers                                   1
r c apartment                                      1
alica nagar chs                                    1
swastik pushkar accord                             1
tilak nagar chs                                    1
jvpd scheme                                        1
yucca                                              1
divya darpan chsl                                  1
horizon highest                                    1
ganga apartment                                    1
chaitanya towers                                   1
ranvir lights                                      1
ranbir life                                        1
nicco recidency andheri east                       1
shethsociety                                       1
white arch                                         1
saruddhi chs                                       1
tiara socirty ltd                                  1
padmavati aadesh                                   1
shital building , jvpd                             1
janki kutir                                        1
11 east                                            1
lake homes                                         1
shree jay shreenath niwas chsl                     1
dattani sun rise                                   1
sukhniwas chs                                      1
hemu castle chs                                    1
aayush ayaansh                                     1
nehru nagar chs                                    1
sanjivani chs                                      1
raj umang 2 chs                                    1
sunrose apartment                                  1
sanghvi heights                                    1
samrath chs                                        1
shimmering heights                                 1
mdchs ltd                                          1
saurabh building                                   1
koyal society chs                                  1
sidhivinayak apurva heights                        1
neelkanth cottage                                  1
raheja reflections eternity                        1
alliance bhaskar                                   1
golf walk apartment                                1
sidhivinayak chetan apartments                     1
chetan chs                                         1
rajkamal pride                                     1

In [ ]:
def standardprice(price):
  if price[1] == 'Crore':
    return round(float(price[0]),2)
  elif price[1] == 'Lac':
    return round((float(price[0])/100),2)

In [ ]:
data['price'] = data['price'].str.split(' ').apply(standardprice)

In [ ]:
data.rename(columns={'price':'price(in Crore)'},inplace=True)

In [ ]:
data.head()

,property_name,society,link,price(in Crore),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"3 BHK Flat in Pant Nagar, Ghatkopar",72 park side,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.70,"₹ 36,815 per sq.ft.",Carpet area: 1005 (93.37 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,"Pooja Room,Study Room,Store Room","11111, Pant Nagar, Ghatkopar",7th of 21 Floors,North-East,0 to 1 Year Old,"['Siddhivinayak Temple', 'ganesh mandir', 'Khu...",This 3 bhk apartment is available for sale in ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",Q79229345
1,"2 BHK Flat in Anjurdive, Thane",lodha upper thane,https://www.99acres.com/2-bhk-bedroom-apartmen...,0.59,"₹ 11,132 per sq.ft.",Carpet area: 530 (49.24 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Anjurdive, Thane",16th of 20 Floors,South-East,1 to 5 Year Old,"['Viviana Mall', 'Supermarket', 'Sai Super Mar...",Lodha upper thane is one of thane outskirts's ...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management3.7 out of 5', 'Green Area4.2 out ...",B75231863
2,"2 BHK Flat in Veera Desai Road, Andheri West",bhairav co op hsg society,https://www.99acres.com/2-bhk-bedroom-apartmen...,2.00,"₹ 26,666 per sq.ft.",Carpet area: 625 (58.06 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"505, B Wing, Veera Desai Road, Andheri West",5th of 7 Floors,North,10+ Year Old,"['Azad nagar metro station', 'D n nagar metro ...",Residential apartment\nThis is your chance to ...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",S79968421
3,"3 BHK Flat in Vile Parle East, Mumbai",samkit apartments,https://www.99acres.com/3-bhk-bedroom-apartmen...,5.33,"₹ 42,500 per sq.ft.",Carpet area: 1254.55 (116.55 sq.m.),3 Bedrooms,4 Bathrooms,No Balcony,Pooja Room,"Vile Parle East, Mumbai",4th of 6 Floors,East,0 to 1 Year Old,"['Jayashree', 'Church', 'Parle Jin Mandir', 'J...",Residential apartment\nThis is your chance to ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.4 out of 5', 'Connectivity4.5 out of...",S80233673
4,"3 BHK Flat in Worli, Mumbai",lodha adrina,https://www.99acres.com/3-bhk-bedroom-apartmen...,7.90,"₹ 69,542 per sq.ft.",Carpet area: 1136 (105.54 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,Servant Room,"Worli, Mumbai",53 of 68 Floors,NaN,Within 6 months,"['Lower Parel Station', 'Asalpha Metro Station...",Residential apartment\nThis is your chance to ...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.3 out of 5', 'Connectivity4.4 out of...",P78904727

In [ ]:
data['price_per_sqft'] = data['price_per_sqft'].str.split('per').str.get(0).str.strip('₹').str.strip(' ').str.replace(',','').astype('float')

In [ ]:
data.head()

,property_name,society,link,price(in Crore),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"3 BHK Flat in Pant Nagar, Ghatkopar",72 park side,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.70,36815.0,Carpet area: 1005 (93.37 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,"Pooja Room,Study Room,Store Room","11111, Pant Nagar, Ghatkopar",7th of 21 Floors,North-East,0 to 1 Year Old,"['Siddhivinayak Temple', 'ganesh mandir', 'Khu...",This 3 bhk apartment is available for sale in ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",Q79229345
1,"2 BHK Flat in Anjurdive, Thane",lodha upper thane,https://www.99acres.com/2-bhk-bedroom-apartmen...,0.59,11132.0,Carpet area: 530 (49.24 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Anjurdive, Thane",16th of 20 Floors,South-East,1 to 5 Year Old,"['Viviana Mall', 'Supermarket', 'Sai Super Mar...",Lodha upper thane is one of thane outskirts's ...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management3.7 out of 5', 'Green Area4.2 out ...",B75231863
2,"2 BHK Flat in Veera Desai Road, Andheri West",bhairav co op hsg society,https://www.99acres.com/2-bhk-bedroom-apartmen...,2.00,26666.0,Carpet area: 625 (58.06 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"505, B Wing, Veera Desai Road, Andheri West",5th of 7 Floors,North,10+ Year Old,"['Azad nagar metro station', 'D n nagar metro ...",Residential apartment\nThis is your chance to ...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",S79968421
3,"3 BHK Flat in Vile Parle East, Mumbai",samkit apartments,https://www.99acres.com/3-bhk-bedroom-apartmen...,5.33,42500.0,Carpet area: 1254.55 (116.55 sq.m.),3 Bedrooms,4 Bathrooms,No Balcony,Pooja Room,"Vile Parle East, Mumbai",4th of 6 Floors,East,0 to 1 Year Old,"['Jayashree', 'Church', 'Parle Jin Mandir', 'J...",Residential apartment\nThis is your chance to ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.4 out of 5', 'Connectivity4.5 out of...",S80233673
4,"3 BHK Flat in Worli, Mumbai",lodha adrina,https://www.99acres.com/3-bhk-bedroom-apartmen...,7.90,69542.0,Carpet area: 1136 (105.54 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,Servant Room,"Worli, Mumbai",53 of 68 Floors,NaN,Within 6 months,"['Lower Parel Station', 'Asalpha Metro Station...",Residential apartment\nThis is your chance to ...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.3 out of 5', 'Connectivity4.4 out of...",P78904727

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2331 entries, 0 to 2526
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2331 non-null   object
 1   society          2331 non-null   object
 2   link             2331 non-null   object
 3   price(in Crore)  2331 non-null   float64
 4   price_per_sqft   2331 non-null   float64
 5   areaWithType     2331 non-null   object
 6   bedRoom          2331 non-null   object
 7   bathroom         2331 non-null   object
 8   balcony          2331 non-null   object
 9   additionalRoom   1364 non-null   object
 10  address          2331 non-null   object
 11  floorNum         2331 non-null   object
 12  facing           2205 non-null   object
 13  agePossession    2330 non-null   object
 14  nearbyLocations  2316 non-null   object
 15  description      2331 non-null   object
 16  furnishDetails   998 non-null    object
 17  features         2307 non-null   object
 18  rating           2251 non-null   object
 19  property_id      2331 non-null   object
dtypes: float64(2), object(18)
memory usage: 447.0+ KB

In [ ]:
data['bedRoom'].value_counts()

bedRoom
2 Bedrooms    1037
3 Bedrooms     836
1 Bedroom      250
4 Bedrooms     179
5 Bedrooms      20
6 Bedrooms       7
7 Bedrooms       1
8 Bedrooms       1
Name: count, dtype: int64

In [ ]:
#data['bedRoom'] = data['bedRoom'].str.split(' ').str.get(0).astype('int')
data['bathroom'] = data['bathroom'].str.split(' ').str.get(0).astype('int')
data['balcony'] = data['balcony'].str.split(' ').str.get(0).astype('int')

ValueError: invalid literal for int() with base 10: 'No'

In [ ]:
data['balcony'] = data['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [ ]:
data['balcony'].value_counts()

balcony
0     1504
1      465
2      141
3      111
3+     110
Name: count, dtype: int64

In [ ]:
data['additionalRoom'].isnull().sum()

967

In [ ]:
data['additionalRoom'].fillna('not available',inplace=True)

In [ ]:
data['additionalRoom'] = data['additionalRoom'].str.lower()

In [ ]:
data.head()

,property_name,society,link,price(in Crore),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"3 BHK Flat in Pant Nagar, Ghatkopar",72 park side,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.70,36815.0,Carpet area: 1005 (93.37 sq.m.),3,3,1,"pooja room,study room,store room","11111, Pant Nagar, Ghatkopar",7th of 21 Floors,North-East,0 to 1 Year Old,"['Siddhivinayak Temple', 'ganesh mandir', 'Khu...",This 3 bhk apartment is available for sale in ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",Q79229345
1,"2 BHK Flat in Anjurdive, Thane",lodha upper thane,https://www.99acres.com/2-bhk-bedroom-apartmen...,0.59,11132.0,Carpet area: 530 (49.24 sq.m.),2,2,0,not available,"Anjurdive, Thane",16th of 20 Floors,South-East,1 to 5 Year Old,"['Viviana Mall', 'Supermarket', 'Sai Super Mar...",Lodha upper thane is one of thane outskirts's ...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management3.7 out of 5', 'Green Area4.2 out ...",B75231863
2,"2 BHK Flat in Veera Desai Road, Andheri West",bhairav co op hsg society,https://www.99acres.com/2-bhk-bedroom-apartmen...,2.00,26666.0,Carpet area: 625 (58.06 sq.m.),2,2,1,not available,"505, B Wing, Veera Desai Road, Andheri West",5th of 7 Floors,North,10+ Year Old,"['Azad nagar metro station', 'D n nagar metro ...",Residential apartment\nThis is your chance to ...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",S79968421
3,"3 BHK Flat in Vile Parle East, Mumbai",samkit apartments,https://www.99acres.com/3-bhk-bedroom-apartmen...,5.33,42500.0,Carpet area: 1254.55 (116.55 sq.m.),3,4,0,pooja room,"Vile Parle East, Mumbai",4th of 6 Floors,East,0 to 1 Year Old,"['Jayashree', 'Church', 'Parle Jin Mandir', 'J...",Residential apartment\nThis is your chance to ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.4 out of 5', 'Connectivity4.5 out of...",S80233673
4,"3 BHK Flat in Worli, Mumbai",lodha adrina,https://www.99acres.com/3-bhk-bedroom-apartmen...,7.90,69542.0,Carpet area: 1136 (105.54 sq.m.),3,3,1,servant room,"Worli, Mumbai",53 of 68 Floors,NaN,Within 6 months,"['Lower Parel Station', 'Asalpha Metro Station...",Residential apartment\nThis is your chance to ...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.3 out of 5', 'Connectivity4.4 out of...",P78904727

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2331 entries, 0 to 2526
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2331 non-null   object
 1   society          2331 non-null   object
 2   link             2331 non-null   object
 3   price(in Crore)  2331 non-null   float64
 4   price_per_sqft   2331 non-null   float64
 5   areaWithType     2331 non-null   object
 6   bedRoom          2331 non-null   int64
 7   bathroom         2331 non-null   int64
 8   balcony          2331 non-null   object
 9   additionalRoom   2331 non-null   object
 10  address          2331 non-null   object
 11  floorNum         2331 non-null   object
 12  facing           2205 non-null   object
 13  agePossession    2330 non-null   object
 14  nearbyLocations  2316 non-null   object
 15  description      2331 non-null   object
 16  furnishDetails   998 non-null    object
 17  features         2307 non-null   object
 18  rating           2251 non-null   object
 19  property_id      2331 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 447.0+ KB

In [ ]:
data['floorNum'].value_counts()

floorNum
4th   of 7 Floors       23
6th   of 7 Floors       22
5th   of 7 Floors       20
10th   of 16 Floors     13
3rd   of 8 Floors       13
6th   of 22 Floors      13
2nd   of 7 Floors       13
8th   of 22 Floors      12
3rd   of 7 Floors       11
14th   of 21 Floors     11
7th   of 20 Floors      11
7th   of 16 Floors      10
7th   of 7 Floors       10
5th   of 8 Floors       10
5th   of 16 Floors      10
18th   of 22 Floors     10
4th   of 16 Floors      10
10th   of 22 Floors     10
3rd   of 13 Floors      10
9th   of 19 Floors      10
5th   of 30 Floors       9
9th   of 12 Floors       9
5th   of 9 Floors        9
5th   of 20 Floors       9
6th   of 12 Floors       9
1st   of 7 Floors        9
17th   of 22 Floors      9
2nd   of 22 Floors       9
6th   of 10 Floors       9
15th   of 23 Floors      9
14th   of 16 Floors      9
11st   of 22 Floors      9
19th   of 22 Floors      9
8th   of 12 Floors       8
4th   of 9 Floors        8
3rd   of 12 Floors       8
6th   of 16 Floors       8
11st   of 13 Floors      8
3rd   of 23 Floors       8
12nd   of 16 Floors      8
7th   of 8 Floors        8
7th   of 9 Floors        8
5th   of 12 Floors       8
Ground of 30 Floors      8
4th   of 22 Floors       8
4th   of 20 Floors       8
16th   of 23 Floors      8
16th   of 20 Floors      8
11st   of 20 Floors      8
17th   of 20 Floors      8
3rd   of 22 Floors       7
3rd   of 9 Floors        7
14th   of 30 Floors      7
20th   of 22 Floors      7
9th   of 21 Floors       7
11st   of 17 Floors      7
10th   of 21 Floors      7
7th   of 22 Floors       7
10th   of 12 Floors      7
12nd   of 17 Floors      7
4th   of 10 Floors       7
12nd   of 15 Floors      7
3rd   of 21 Floors       7
10th   of 40 Floors      7
2nd   of 18 Floors       7
13rd   of 15 Floors      7
10th   of 15 Floors      7
7th   of 14 Floors       7
4th   of 8 Floors        7
16th   of 22 Floors      7
9th   of 17 Floors       7
4th   of 24 Floors       7
8th   of 16 Floors       7
2nd   of 21 Floors       7
2nd   of 20 Floors       7
12nd   of 20 Floors      7
13rd   of 40 Floors      7
14th   of 44 Floors      6
9th   of 23 Floors       6
11st   of 16 Floors      6
10th   of 41 Floors      6
18th   of 20 Floors      6
4th   of 14 Floors       6
5th   of 22 Floors       6
10th   of 18 Floors      6
4th   of 30 Floors       6
19th   of 20 Floors      6
22nd   of 40 Floors      6
7th   of 10 Floors       6
10th   of 28 Floors      6
3rd   of 17 Floors       6
11st   of 15 Floors      6
8th   of 14 Floors       6
21st   of 22 Floors      6
6th   of 6 Floors        6
4th   of 18 Floors       6
1st   of 30 Floors       6
1st   of 8 Floors        6
6th   of 9 Floors        6
8th   of 13 Floors       6
13rd   of 14 Floors      6
8th   of 20 Floors       6
10th   of 14 Floors      6
7th   of 17 Floors       6
11st   of 30 Floors      6
20th   of 30 Floors      6
12nd   of 22 Floors      6
20th   of 40 Floors      6
2nd   of 8 Floors        5
4th   of 19 Floors       5
15th   of 40 Floors      5
32nd   of 44 Floors      5
10th   of 30 Floors      5
13rd   of 61 Floors      5
34th   of 41 Floors      5
7th   of 12 Floors       5
8th   of 15 Floors       5
7th   of 15 Floors       5
3rd   of 16 Floors       5
16th   of 30 Floors      5
10th   of 20 Floors      5
14th   of 22 Floors      5
5th   of 13 Floors       5
9th   of 16 Floors       5
5th   of 10 Floors       5
15th   of 35 Floors      5
23rd   of 30 Floors      5
2nd   of 15 Floors       5
3rd   of 19 Floors       5
3rd   of 14 Floors       5
15th   of 21 Floors      5
11st   of 44 Floors      5
12nd   of 19 Floors      5
16th   of 19 Floors      5
11st   of 23 Floors      5
10th   of 17 Floors      5
18th   of 30 Floors      5
11st   of 11 Floors      5
28th   of 40 Floors      5
19th   of 21 Floors      5
15th   of 22 Floors      5
8th   of 19 Floors       5
19th   of 23 Floors      5
15th   of 17 Floors      5
7th   of 13 Floors       5
12nd   of 61 Floors      4
25th   of 47 Floors      4
2nd   of 16 Floors       4
9th   of 15 Floors       4
9th   of 22 Floors       4
18th   of 21 Floors      4
6th   of 14 Floors       4
15th   of 16 Floors      4
3rd   of 20 Floors       4
4th   of 15 Floors       4
8th   of 9 Floors        4
6th   of 24 Floors       4
6th   of 13 Floors       4
20th   of 38 Floors      4
9th   of 9 Floors        4
9th   of 18 Floors       4
19th   of 44 Floors      4
2nd   of 11 Floors       4
5th   of 19 Floors       4
5th   of 18 Floors       4
21st   of 30 Floors      4
17th   of 24 Floors      4
20th   of 23 Floors      4
32nd   of 34 Floors      4
8th   of 30 Floors       4
18th   of 38 Floors      4
7th   of 18 Floors       4
12nd   of 14 Floors      4
Ground of 3 Floors       4
14th   of 28 Floors      4
10th   of 19 Floors      4
14th   of 17 Floors      4
12nd   of 40 Floors      4
8th   of 10 Floors       4
12nd   of 13 Floors      4
6th   of 20 Floors       4
14th   of 20 Floors      4
4th   of 11 Floors       4
3rd   of 18 Floors       4
13rd   of 16 Floors      4
16th   of 44 Floors      4
13rd   of 42 Floors      4
25th   of 50 Floors      4
33rd   of 40 Floors      4
7th   of 23 Floors       4
13rd   of 17 Floors      4
3rd   of 24 Floors       4
24th   of 42 Floors      4
10th   of 13 Floors      4
12nd   of 47 Floors      4
30th   of 47 Floors      3
7th   of 33 Floors       3
14th   of 33 Floors      3
14th   of 35 Floors      3
2nd   of 14 Floors       3
12nd   of 38 Floors      3
6th   of 15 Floors       3
12nd   of 18 Floors      3
15th   of 24 Floors      3
5th   of 26 Floors       3
4th   of 38 Floors       3
18th   of 43 Floors      3
9th   of 38 Floors       3
9th   of 10 Floors       3
18th   of 24 Floors      3
18th   of 19 Floors      3
11st   of 19 Floors      3
5th   of 14 Floors       3
21st   of 28 Floors      3
10th   of 23 Floors      3
5th   of 23 Floors       3
40th   of 79 Floors      3
15th   of 61 Floors      3
15th   of 18 Floors      3
10th   of 35 Floors      3
20th   of 24 Floors      3
10th   of 10 Floors      3
17th   of 37 Floors      3
8th   of 24 Floors       3
2nd   of 24 Floors       3
17th   of 26 Floors      3
13rd   of 22 Floors      3
9th   of 14 Floors       3
30th   of 36 Floors      3
18th   of 40 Floors      3
7th   of 21 Floors       3
14th   of 23 Floors      3
30th   of 43 Floors      3
13rd   of 28 Floors      3
17th   of 19 Floors      3
2nd   of 17 Floors       3
10th   of 47 Floors      3
2nd   of 9 Floors        3
3rd   of 6 Floors        3
34th   of 40 Floors      3
13rd   of 24 Floors      3
21st   of 21 Floors      3
6th   of 8 Floors        3
6th   of 31 Floors       3
11st   of 14 Floors      3
20th   of 21 Floors      3
1st   of 9 Floors        3
13rd   of 21 Floors      3
23rd   of 40 Floors      3
1st   of 3 Floors        3
2nd   of 12 Floors       3
17th   of 28 Floors      3
15th   of 43 Floors      3
15th   of 15 Floors      3
18th   of 23 Floors      3
1st   of 17 Floors       3
13rd   of 47 Floors      3
34th   of 37 Floors      3
23rd   of 37 Floors      3
18th   of 28 Floors      3
1st   of 11 Floors       3
23rd   of 41 Floors      3
14th   of 34 Floors      3
19th   of 40 Floors      3
12nd   of 28 Floors      3
10th   of 25 Floors      3
30th   of 34 Floors      3
15th   of 47 Floors      3
8th   of 11 Floors       3
9th   of 41 Floors       3
23rd   of 24 Floors      3
36th   of 61 Floors      3
4th   of 31 Floors       3
16th   of 34 Floors      3
4th   of 5 Floors        3
17th   of 64 Floors      3
16th   of 18 Floors      3
43   of 43 Floors        3
15th   of 44 Floors      3
25th   of 64 Floors      3
16th   of 16 Floors      2
16th   of 46 Floors      2
6th   of 18 Floors       2
14th   of 19 Floors      2
3rd   of 5 Floors        2
8th   of 40 Floors       2
6th   of 11 Floors       2
6th   of 23 Floors       2
25th   of 41 Floors      2
23rd   of 65 Floors      2
14th   of 15 Floors      2
19th   of 30 Floors      2
5th   of 55 Floors       2
13rd   of 30 Floors      2
7th   of 24 Floors       2
5th   of 15 Floors       2
8th   of 17 Floors       2
25th   of 40 Floors      2
5th   of 41 Floors       2
35th   of 40 Floors      2
5th   of 17 Floors       2
15th   of 25 Floors      2
36th   of 47 Floors      2
15th   of 27 Floors      2
30th   of 72 Floors      2
3rd   of 27 Floors       2
7th   of 26 Floors       2
26th   of 30 Floors      2
8th   of 60 Floors       2
10th   of 43 Floors      2
33rd   of 39 Floors      2
37th   of 47 Floors      2
5th   of 40 Floors       2
29th   of 79 Floors      2
4th   of 17 Floors       2
29th   of 40 Floors      2
26th   of 47 Floors      2
6th   of 41 Floors       2
15th   of 28 Floors      2
14th   of 27 Floors      2
23rd   of 52 Floors      2
26th   of 52 Floors      2
9th   of 30 Floors       2
16th   of 43 Floors      2
32nd   of 38 Floors      2
23rd   of 44 Floors      2
15th   of 42 Floors      2
27th   of 42 Floors      2
32nd   of 62 Floors      2
23rd   of 34 Floors      2
15th   of 34 Floors      2
22nd   of 38 Floors      2
8th   of 18 Floors       2
21st   of 38 Floors      2
6th   of 28 Floors       2
17th   of 23 Floors      2
5th   of 11 Floors       2
5th   of 21 Floors       2
45   of 50 Floors        2
10th   of 60 Floors      2
11st   of 18 Floors      2
26th   of 28 Floors      2
14th   of 43 Floors      2
18th   of 64 Floors      2
28th   of 52 Floors      2
33rd   of 42 Floors      2
36th   of 42 Floors      2
36th   of 38 Floors      2
24th   of 43 Floors      2
8th   of 41 Floors       2
17th   of 38 Floors      2
42   of 64 Floors        2
35th   of 47 Floors      2
15th   of 70 Floors      2
33rd   of 34 Floors      2
6th   of 27 Floors       2
11st   of 61 Floors      2
37th   of 44 Floors      2
20th   of 28 Floors      2
2nd   of 23 Floors       2
8th   of 35 Floors       2
21st   of 23 Floors      2
1st   of 24 Floors       2
11st   of 21 Floors      2
31st   of 71 Floors      2
16th   of 21 Floors      2
10th   of 52 Floors      2
19th   of 55 Floors      2
38th   of 40 Floors      2
21st   of 43 Floors      2
22nd   of 47 Floors      2
17th   of 21 Floors      2
19th   of 19 Floors      2
10th   of 11 Floors      2
27th   of 28 Floors      2
2nd   of 10 Floors       2
26th   of 57 Floors      2
42   of 57 Floors        2
25th   of 44 Floors      2
13rd   of 44 Floors      2
21st   of 44 Floors      2
18th   of 44 Floors      2
6th   of 17 Floors       2
14th   of 40 Floors      2
28th   of 30 Floors      2
2nd   of 38 Floors       2
43   of 47 Floors        2
20th   of 33 Floors      2
12nd   of 21 Floors      2
25th   of 59 Floors      2
11st   of 27 Floors      2
9th   of 47 Floors       2
7th   of 11 Floors       2
17th   of 30 Floors      2
21st   of 34 Floors      2
12nd   of 27 Floors      2
7th   of 38 Floors       2
20th   of 72 Floors      2
12nd   of 23 Floors      2
17th   of 40 Floors      2
13rd   of 23 Floors      2
11st   of 28 Floors      2
27th   of 40 Floors      2
15th   of 30 Floors      2
8th   of 21 Floors       2
22nd   of 25 Floors      2
22nd   of 41 Floors      2
16th   of 28 Floors      2
40th   of 63 Floors      2
14th   of 47 Floors      2
33rd   of 36 Floors      2
4th   of 12 Floors       2
19th   of 28 Floors      2
31st   of 57 Floors      2
7th   of 19 Floors       2
15th   of 19 Floors      2
28th   of 36 Floors      2
3rd   of 3 Floors        2
4th   of 4 Floors        2
3rd   of 4 Floors        2
1st   of 6 Floors        2
20th   of 20 Floors      2
5th   of 25 Floors       2
1st   of 10 Floors       2
1st   of 19 Floors       2
4th   of 6 Floors        2
2nd   of 4 Floors        2
2nd   of 2 Floors        2
21st   of 40 Floors      2
35th   of 41 Floors      2
30th   of 71 Floors      2
9th   of 13 Floors       2
Ground of 4 Floors       2
13rd   of 20 Floors      2
12nd   of 12 Floors      2
29th   of 44 Floors      2
28th   of 47 Floors      2
33rd   of 68 Floors      2
40th   of 47 Floors      2
18th   of 47 Floors      2
13rd   of 19 Floors      2
9th   of 20 Floors       2
30th   of 42 Floors      2
6th   of 42 Floors       2
5th   of 28 Floors       2
5th   of 38 Floors       2
30th   of 38 Floors      2
15th   of 20 Floors      2
1st   of 21 Floors       2
7th   of 28 Floors       2
3rd   of 15 Floors       2
4th   of 13 Floors       2
27th   of 44 Floors      2
21st   of 72 Floors      2
16th   of 33 Floors      2
28th   of 44 Floors      2
33rd   of 44 Floors      2
8th   of 23 Floors       2
16th   of 40 Floors      2
11st   of 12 Floors      2
6th   of 33 Floors       2
20th   of 44 Floors      2
23rd   of 79 Floors      2
13rd   of 18 Floors      2
16th   of 26 Floors      2
29th   of 38 Floors      2
12nd   of 46 Floors      2
23rd   of 72 Floors      2
3rd   of 26 Floors       2
22nd   of 23 Floors      2
6th   of 52 Floors       2
38th   of 77 Floors      2
14th   of 31 Floors      2
42   of 62 Floors        1
3rd   of 30 Floors       1
55   of 59 Floors        1
1st   of 27 Floors       1
10th   of 44 Floors      1
24th   of 37 Floors      1
8th   of 47 Floors       1
33rd   of 46 Floors      1
2nd   of 46 Floors       1
30th   of 32 Floors      1
27th   of 64 Floors      1
32nd   of 71 Floors      1
11st   of 26 Floors      1
40th   of 117 Floors     1
17th   of 47 Floors      1
20th   of 42 Floors      1
8th   of 58 Floors       1
13rd   of 31 Floors      1
57   of 61 Floors        1
6th   of 58 Floors       1
30th   of 49 Floors      1
23rd   of 49 Floors      1
12nd   of 31 Floors      1
24th   of 38 Floors      1
70   of 74 Floors        1
15th   of 26 Floors      1
42   of 71 Floors        1
11st   of 55 Floors      1
44   of 72 Floors        1
55   of 72 Floors        1
23rd   of 64 Floors      1
20th   of 64 Floors      1
6th   of 26 Floors       1
22nd   of 79 Floors      1
40th   of 71 Floors      1
18th   of 42 Floors      1
14th   of 50 Floors      1
34th   of 77 Floors      1
27th   of 33 Floors      1
17th   of 52 Floors      1
52   of 57 Floors        1
12nd   of 58 Floors      1
38th   of 39 Floors      1
19th   of 26 Floors      1
13rd   of 36 Floors      1
14th   of 26 Floors      1
12nd   of 44 Floors      1
9th   of 25 Floors       1
61   of 72 Floors        1
38th   of 52 Floors      1
20th   of 41 Floors      1
27th   of 52 Floors      1
22nd   of 52 Floors      1
22nd   of 61 Floors      1
31st   of 35 Floors      1
27th   of 29 Floors      1
24th   of 72 Floors      1
38th   of 57 Floors      1
31st   of 44 Floors      1
35th   of 36 Floors      1
5th   of 24 Floors       1
12nd   of 73 Floors      1
37th   of 53 Floors      1
17th   of 79 Floors      1
12nd   of 24 Floors      1
9th   of 26 Floors       1
24th   of 50 Floors      1
43   of 68 Floors        1
17th   of 44 Floors      1
19th   of 24 Floors      1
26th   of 40 Floors      1
20th   of 35 Floors      1
34th   of 53 Floors      1
32nd   of 52 Floors      1
43   of 72 Floors        1
24th   of 48 Floors      1
8th   of 44 Floors       1
9th   of 44 Floors       1
45   of 67 Floors        1
22nd   of 34 Floors      1
14th   of 14 Floors      1
12nd   of 50 Floors      1
29th   of 50 Floors      1
14th   of 61 Floors      1
11st   of 34 Floors      1
21st   of 33 Floors      1
25th   of 37 Floors      1
17th   of 33 Floors      1
26th   of 33 Floors      1
30th   of 70 Floors      1
36th   of 43 Floors      1
29th   of 33 Floors      1
31st   of 79 Floors      1
14th   of 75 Floors      1
15th   of 62 Floors      1
28th   of 33 Floors      1
35th   of 70 Floors      1
22nd   of 72 Floors      1
17th   of 18 Floors      1
25th   of 61 Floors      1
30th   of 65 Floors      1
33rd   of 62 Floors      1
32nd   of 36 Floors      1
18th   of 36 Floors      1
49   of 68 Floors        1
32nd   of 43 Floors      1
7th   of 34 Floors       1
10th   of 59 Floors      1
12nd   of 57 Floors      1
7th   of 41 Floors       1
10th   of 61 Floors      1
13rd   of 35 Floors      1
25th   of 42 Floors      1
11st   of 39 Floors      1
33rd   of 52 Floors      1
1st   of 14 Floors       1
24th   of 41 Floors      1
20th   of 34 Floors      1
3rd   of 34 Floors       1
20th   of 59 Floors      1
12nd   of 30 Floors      1
16th   of 59 Floors      1
39th   of 75 Floors      1
47   of 62 Floors        1
34th   of 47 Floors      1
21st   of 59 Floors      1
9th   of 34 Floors       1
5th   of 34 Floors       1
4th   of 36 Floors       1
18th   of 31 Floors      1
54   of 72 Floors        1
12nd   of 41 Floors      1
5th   of 33 Floors       1
28th   of 58 Floors      1
45   of 64 Floors        1
42   of 42 Floors        1
38th   of 61 Floors      1
24th   of 31 Floors      1
20th   of 57 Floors      1
52   of 61 Floors        1
10th   of 46 Floors      1
19th   of 27 Floors      1
6th   of 35 Floors       1
27th   of 41 Floors      1
7th   of 36 Floors       1
25th   of 38 Floors      1
23rd   of 47 Floors      1
16th   of 36 Floors      1
29th   of 47 Floors      1
12nd   of 34 Floors      1
Ground of 6 Floors       1
37th   of 50 Floors      1
40th   of 42 Floors      1
8th   of 28 Floors       1
27th   of 47 Floors      1
9th   of 24 Floors       1
10th   of 62 Floors      1
9th   of 33 Floors       1
24th   of 36 Floors      1
14th   of 62 Floors      1
26th   of 34 Floors      1
12nd   of 62 Floors      1
9th   of 60 Floors       1
22nd   of 30 Floors      1
12nd   of 25 Floors      1
53   of 78 Floors        1
53   of 57 Floors        1
14th   of 24 Floors      1
10th   of 38 Floors      1
7th   of 60 Floors       1
4th   of 47 Floors       1
12nd   of 26 Floors      1
24th   of 67 Floors      1
34th   of 57 Floors      1
16th   of 38 Floors      1
11st   of 57 Floors      1
27th   of 38 Floors      1
2nd   of 3 Floors        1
35th   of 43 Floors      1
9th   of 35 Floors       1
1st   of 16 Floors       1
32nd   of 35 Floors      1
6th   of 55 Floors       1
19th   of 75 Floors      1
26th   of 31 Floors      1
3rd   of 48 Floors       1
26th   of 44 Floors      1
26th   of 59 Floors      1
4th   of 23 Floors       1
35th   of 64 Floors      1
18th   of 39 Floors      1
29th   of 30 Floors      1
59   of 64 Floors        1
30th   of 64 Floors      1
4th   of 52 Floors       1
21st   of 75 Floors      1
21st   of 67 Floors      1
10th   of 32 Floors      1
36th   of 40 Floors      1
30th   of 117 Floors     1
2nd   of 27 Floors       1
6th   of 50 Floors       1
Ground of 7 Floors       1
20th   of 56 Floors      1
4th   of 41 Floors       1
21st   of 61 Floors      1
13rd   of 26 Floors      1
22nd   of 22 Floors      1
37th   of 40 Floors      1
27th   of 27 Floors      1
2nd   of 48 Floors       1
3rd   of 55 Floors       1
25th   of 52 Floors      1
50   of 65 Floors        1
33rd   of 38 Floors      1
11st   of 38 Floors      1
7th   of 43 Floors       1
20th   of 31 Floors      1
40th   of 40 Floors      1
21st   of 36 Floors      1
36th   of 37 Floors      1
35th   of 42 Floors      1
28th   of 72 Floors      1
26th   of 53 Floors      1
13rd   of 79 Floors      1
20th   of 37 Floors      1
9th   of 11 Floors       1
58   of 80 Floors        1
45   of 65 Floors        1
13rd   of 46 Floors      1
35th   of 79 Floors      1
3rd   of 11 Floors       1
32nd   of 47 Floors      1
40th   of 67 Floors      1
22nd   of 70 Floors      1
32nd   of 50 Floors      1
31st   of 90 Floors      1
35th   of 38 Floors      1
48   of 79 Floors        1
18th   of 59 Floors      1
34th   of 50 Floors      1
3rd   of 29 Floors       1
34th   of 36 Floors      1
31st   of 48 Floors      1
17th   of 25 Floors      1
20th   of 62 Floors      1
39th   of 41 Floors      1
30th   of 61 Floors      1
32nd   of 57 Floors      1
26th   of 43 Floors      1
17th   of 48 Floors      1
16th   of 54 Floors      1
31st   of 72 Floors      1
8th   of 29 Floors       1
16th   of 42 Floors      1
Ground of 12 Floors      1
27th   of 62 Floors      1
55   of 63 Floors        1
13rd   of 25 Floors      1
34th   of 43 Floors      1
4th   of 33 Floors       1
31st   of 32 Floors      1
35th   of 63 Floors      1
46   of 50 Floors        1
12nd   of 36 Floors      1
7th   of 27 Floors       1
13rd   of 27 Floors      1

In [ ]:
data['floorNum'] = data['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Lower','0').str.extract(r'(\d+)')

In [ ]:
data['floorNum'].value_counts()

floorNum
4     136
5     135
10    130
3     126
6     125
7     121
8      96
11     95
12     94
9      92
2      92
14     86
15     81
13     73
16     68
18     60
20     59
17     55
19     53
1      50
21     38
23     38
25     30
30     29
22     27
32     23
33     23
28     22
24     22
26     21
27     21
35     18
0      18
34     18
31     17
29     16
40     15
36     13
37     12
43     11
38     11
45      9
42      8
39      7
55      5
41      4
47      3
52      3
53      3
57      2
50      2
49      2
51      2
70      1
54      1
56      1
44      1
48      1
58      1
59      1
60      1
67      1
46      1
61      1
Name: count, dtype: int64

In [ ]:
data['facing'].isnull().sum()

126

In [ ]:
data['facing'].fillna('not available',inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2331 entries, 0 to 2526
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2331 non-null   object
 1   society          2331 non-null   object
 2   link             2331 non-null   object
 3   price(in Crore)  2331 non-null   float64
 4   price_per_sqft   2331 non-null   float64
 5   areaWithType     2331 non-null   object
 6   bedRoom          2331 non-null   int64
 7   bathroom         2331 non-null   int64
 8   balcony          2331 non-null   object
 9   additionalRoom   2331 non-null   object
 10  address          2331 non-null   object
 11  floorNum         2331 non-null   object
 12  facing           2331 non-null   object
 13  agePossession    2330 non-null   object
 14  nearbyLocations  2316 non-null   object
 15  description      2331 non-null   object
 16  furnishDetails   998 non-null    object
 17  features         2307 non-null   object
 18  rating           2251 non-null   object
 19  property_id      2331 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 447.0+ KB

In [ ]:
data.head()

,property_name,society,link,price(in Crore),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"3 BHK Flat in Pant Nagar, Ghatkopar",72 park side,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.70,36815.0,Carpet area: 1005 (93.37 sq.m.),3,3,1,"pooja room,study room,store room","11111, Pant Nagar, Ghatkopar",7,North-East,0 to 1 Year Old,"['Siddhivinayak Temple', 'ganesh mandir', 'Khu...",This 3 bhk apartment is available for sale in ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",Q79229345
1,"2 BHK Flat in Anjurdive, Thane",lodha upper thane,https://www.99acres.com/2-bhk-bedroom-apartmen...,0.59,11132.0,Carpet area: 530 (49.24 sq.m.),2,2,0,not available,"Anjurdive, Thane",16,South-East,1 to 5 Year Old,"['Viviana Mall', 'Supermarket', 'Sai Super Mar...",Lodha upper thane is one of thane outskirts's ...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management3.7 out of 5', 'Green Area4.2 out ...",B75231863
2,"2 BHK Flat in Veera Desai Road, Andheri West",bhairav co op hsg society,https://www.99acres.com/2-bhk-bedroom-apartmen...,2.00,26666.0,Carpet area: 625 (58.06 sq.m.),2,2,1,not available,"505, B Wing, Veera Desai Road, Andheri West",5,North,10+ Year Old,"['Azad nagar metro station', 'D n nagar metro ...",Residential apartment\nThis is your chance to ...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",S79968421
3,"3 BHK Flat in Vile Parle East, Mumbai",samkit apartments,https://www.99acres.com/3-bhk-bedroom-apartmen...,5.33,42500.0,Carpet area: 1254.55 (116.55 sq.m.),3,4,0,pooja room,"Vile Parle East, Mumbai",4,East,0 to 1 Year Old,"['Jayashree', 'Church', 'Parle Jin Mandir', 'J...",Residential apartment\nThis is your chance to ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.4 out of 5', 'Connectivity4.5 out of...",S80233673
4,"3 BHK Flat in Worli, Mumbai",lodha adrina,https://www.99acres.com/3-bhk-bedroom-apartmen...,7.90,69542.0,Carpet area: 1136 (105.54 sq.m.),3,3,1,servant room,"Worli, Mumbai",53,not available,Within 6 months,"['Lower Parel Station', 'Asalpha Metro Station...",Residential apartment\nThis is your chance to ...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.3 out of 5', 'Connectivity4.4 out of...",P78904727

In [ ]:
data.insert(loc=4,column='area',value=round((data['price(in Crore)']*10000000)/data['price_per_sqft']))

In [ ]:
data.head()

,property_name,society,link,price(in Crore),area,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"3 BHK Flat in Pant Nagar, Ghatkopar",72 park side,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.70,1005.0,36815.0,Carpet area: 1005 (93.37 sq.m.),3,3,1,"pooja room,study room,store room","11111, Pant Nagar, Ghatkopar",7,North-East,0 to 1 Year Old,"['Siddhivinayak Temple', 'ganesh mandir', 'Khu...",This 3 bhk apartment is available for sale in ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",Q79229345
1,"2 BHK Flat in Anjurdive, Thane",lodha upper thane,https://www.99acres.com/2-bhk-bedroom-apartmen...,0.59,530.0,11132.0,Carpet area: 530 (49.24 sq.m.),2,2,0,not available,"Anjurdive, Thane",16,South-East,1 to 5 Year Old,"['Viviana Mall', 'Supermarket', 'Sai Super Mar...",Lodha upper thane is one of thane outskirts's ...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management3.7 out of 5', 'Green Area4.2 out ...",B75231863
2,"2 BHK Flat in Veera Desai Road, Andheri West",bhairav co op hsg society,https://www.99acres.com/2-bhk-bedroom-apartmen...,2.00,750.0,26666.0,Carpet area: 625 (58.06 sq.m.),2,2,1,not available,"505, B Wing, Veera Desai Road, Andheri West",5,North,10+ Year Old,"['Azad nagar metro station', 'D n nagar metro ...",Residential apartment\nThis is your chance to ...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",S79968421
3,"3 BHK Flat in Vile Parle East, Mumbai",samkit apartments,https://www.99acres.com/3-bhk-bedroom-apartmen...,5.33,1254.0,42500.0,Carpet area: 1254.55 (116.55 sq.m.),3,4,0,pooja room,"Vile Parle East, Mumbai",4,East,0 to 1 Year Old,"['Jayashree', 'Church', 'Parle Jin Mandir', 'J...",Residential apartment\nThis is your chance to ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.4 out of 5', 'Connectivity4.5 out of...",S80233673
4,"3 BHK Flat in Worli, Mumbai",lodha adrina,https://www.99acres.com/3-bhk-bedroom-apartmen...,7.90,1136.0,69542.0,Carpet area: 1136 (105.54 sq.m.),3,3,1,servant room,"Worli, Mumbai",53,not available,Within 6 months,"['Lower Parel Station', 'Asalpha Metro Station...",Residential apartment\nThis is your chance to ...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.3 out of 5', 'Connectivity4.4 out of...",P78904727

In [ ]:
data.insert(loc=1,column='property_type',value='flat')

In [ ]:
data.head()

,property_name,property_type,society,link,price(in Crore),area,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"3 BHK Flat in Pant Nagar, Ghatkopar",flat,72 park side,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.70,1005.0,36815.0,Carpet area: 1005 (93.37 sq.m.),3,3,1,"pooja room,study room,store room","11111, Pant Nagar, Ghatkopar",7,North-East,0 to 1 Year Old,"['Siddhivinayak Temple', 'ganesh mandir', 'Khu...",This 3 bhk apartment is available for sale in ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",Q79229345
1,"2 BHK Flat in Anjurdive, Thane",flat,lodha upper thane,https://www.99acres.com/2-bhk-bedroom-apartmen...,0.59,530.0,11132.0,Carpet area: 530 (49.24 sq.m.),2,2,0,not available,"Anjurdive, Thane",16,South-East,1 to 5 Year Old,"['Viviana Mall', 'Supermarket', 'Sai Super Mar...",Lodha upper thane is one of thane outskirts's ...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management3.7 out of 5', 'Green Area4.2 out ...",B75231863
2,"2 BHK Flat in Veera Desai Road, Andheri West",flat,bhairav co op hsg society,https://www.99acres.com/2-bhk-bedroom-apartmen...,2.00,750.0,26666.0,Carpet area: 625 (58.06 sq.m.),2,2,1,not available,"505, B Wing, Veera Desai Road, Andheri West",5,North,10+ Year Old,"['Azad nagar metro station', 'D n nagar metro ...",Residential apartment\nThis is your chance to ...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.1 out of 5', 'Connectivity4.2 out of...",S79968421
3,"3 BHK Flat in Vile Parle East, Mumbai",flat,samkit apartments,https://www.99acres.com/3-bhk-bedroom-apartmen...,5.33,1254.0,42500.0,Carpet area: 1254.55 (116.55 sq.m.),3,4,0,pooja room,"Vile Parle East, Mumbai",4,East,0 to 1 Year Old,"['Jayashree', 'Church', 'Parle Jin Mandir', 'J...",Residential apartment\nThis is your chance to ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.4 out of 5', 'Connectivity4.5 out of...",S80233673
4,"3 BHK Flat in Worli, Mumbai",flat,lodha adrina,https://www.99acres.com/3-bhk-bedroom-apartmen...,7.90,1136.0,69542.0,Carpet area: 1136 (105.54 sq.m.),3,3,1,servant room,"Worli, Mumbai",53,not available,Within 6 months,"['Lower Parel Station', 'Asalpha Metro Station...",Residential apartment\nThis is your chance to ...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.3 out of 5', 'Connectivity4.4 out of...",P78904727

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2331 entries, 0 to 2526
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2331 non-null   object
 1   property_type    2331 non-null   object
 2   society          2331 non-null   object
 3   link             2331 non-null   object
 4   price(in Crore)  2331 non-null   float64
 5   area             2331 non-null   float64
 6   price_per_sqft   2331 non-null   float64
 7   areaWithType     2331 non-null   object
 8   bedRoom          2331 non-null   int64
 9   bathroom         2331 non-null   int64
 10  balcony          2331 non-null   object
 11  additionalRoom   2331 non-null   object
 12  address          2331 non-null   object
 13  floorNum         2331 non-null   object
 14  facing           2331 non-null   object
 15  agePossession    2330 non-null   object
 16  nearbyLocations  2316 non-null   object
 17  description      2331 non-null   object
 18  furnishDetails   998 non-null    object
 19  features         2307 non-null   object
 20  rating           2251 non-null   object
 21  property_id      2331 non-null   object
dtypes: float64(3), int64(2), object(17)
memory usage: 483.4+ KB

In [ ]:
data.drop(columns=['property_id'], inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2331 entries, 0 to 2526
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2331 non-null   object
 1   property_type    2331 non-null   object
 2   society          2331 non-null   object
 3   link             2331 non-null   object
 4   price(in Crore)  2331 non-null   float64
 5   area             2331 non-null   float64
 6   price_per_sqft   2331 non-null   float64
 7   areaWithType     2331 non-null   object
 8   bedRoom          2331 non-null   int64
 9   bathroom         2331 non-null   int64
 10  balcony          2331 non-null   object
 11  additionalRoom   2331 non-null   object
 12  address          2331 non-null   object
 13  floorNum         2331 non-null   object
 14  facing           2331 non-null   object
 15  agePossession    2330 non-null   object
 16  nearbyLocations  2316 non-null   object
 17  description      2331 non-null   object
 18  furnishDetails   998 non-null    object
 19  features         2307 non-null   object
 20  rating           2251 non-null   object
dtypes: float64(3), int64(2), object(16)
memory usage: 465.2+ KB

In [ ]:
data.duplicated().sum()

34

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
data.shape

(2297, 21)

In [ ]:
data.isnull().sum()

property_name         0
property_type         0
society               0
link                  0
price(in Crore)       0
area                  0
price_per_sqft        0
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address               0
floorNum              0
facing                0
agePossession         1
nearbyLocations      15
description           0
furnishDetails     1316
features             24
rating               80
dtype: int64

In [ ]:
data.insert(loc=3,column='location',value=data['property_name'].str.split('in').str.get(1).str.replace('Mumbai','').str.strip())

In [ ]:
data['location'] = data['location'].str.lower()

In [ ]:
data.head()

,property_name,property_type,society,location,link,price(in Crore),area,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,"3 BHK Flat in Pant Nagar, Ghatkopar",flat,72 park side,"pant nagar, ghatkopar",https://www.99acres.com/3-bhk-bedroom-apartmen...,3.70,1005.0,36815.0,Carpet area: 1005 (93.37 sq.m.),3,3,1,"pooja room,study room,store room","11111, Pant Nagar, Ghatkopar",7,North-East,0 to 1 Year Old,"['Siddhivinayak Temple', 'ganesh mandir', 'Khu...",This 3 bhk apartment is available for sale in ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.1 out of 5', 'Connectivity4.2 out of..."
1,"2 BHK Flat in Anjurdive, Thane",flat,lodha upper thane,"anjurdive, thane",https://www.99acres.com/2-bhk-bedroom-apartmen...,0.59,530.0,11132.0,Carpet area: 530 (49.24 sq.m.),2,2,0,not available,"Anjurdive, Thane",16,South-East,1 to 5 Year Old,"['Viviana Mall', 'Supermarket', 'Sai Super Mar...",Lodha upper thane is one of thane outskirts's ...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management3.7 out of 5', 'Green Area4.2 out ..."
2,"2 BHK Flat in Veera Desai Road, Andheri West",flat,bhairav co op hsg society,"veera desai road, andheri west",https://www.99acres.com/2-bhk-bedroom-apartmen...,2.00,750.0,26666.0,Carpet area: 625 (58.06 sq.m.),2,2,1,not available,"505, B Wing, Veera Desai Road, Andheri West",5,North,10+ Year Old,"['Azad nagar metro station', 'D n nagar metro ...",Residential apartment\nThis is your chance to ...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.1 out of 5', 'Connectivity4.2 out of..."
3,"3 BHK Flat in Vile Parle East, Mumbai",flat,samkit apartments,"vile parle east,",https://www.99acres.com/3-bhk-bedroom-apartmen...,5.33,1254.0,42500.0,Carpet area: 1254.55 (116.55 sq.m.),3,4,0,pooja room,"Vile Parle East, Mumbai",4,East,0 to 1 Year Old,"['Jayashree', 'Church', 'Parle Jin Mandir', 'J...",Residential apartment\nThis is your chance to ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4.4 out of 5', 'Connectivity4.5 out of..."
4,"3 BHK Flat in Worli, Mumbai",flat,lodha adrina,"worli,",https://www.99acres.com/3-bhk-bedroom-apartmen...,7.90,1136.0,69542.0,Carpet area: 1136 (105.54 sq.m.),3,3,1,servant room,"Worli, Mumbai",53,not available,Within 6 months,"['Lower Parel Station', 'Asalpha Metro Station...",Residential apartment\nThis is your chance to ...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety4.3 out of 5', 'Connectivity4.4 out of..."

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2297 entries, 0 to 2526
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2297 non-null   object
 1   property_type    2297 non-null   object
 2   society          2297 non-null   object
 3   location         2297 non-null   object
 4   link             2297 non-null   object
 5   price(in Crore)  2297 non-null   float64
 6   area             2297 non-null   float64
 7   price_per_sqft   2297 non-null   float64
 8   areaWithType     2297 non-null   object
 9   bedRoom          2297 non-null   int64
 10  bathroom         2297 non-null   int64
 11  balcony          2297 non-null   object
 12  additionalRoom   2297 non-null   object
 13  address          2297 non-null   object
 14  floorNum         2297 non-null   object
 15  facing           2297 non-null   object
 16  agePossession    2296 non-null   object
 17  nearbyLocations  2282 non-null   object
 18  description      2297 non-null   object
 19  furnishDetails   981 non-null    object
 20  features         2273 non-null   object
 21  rating           2217 non-null   object
dtypes: float64(3), int64(2), object(17)
memory usage: 412.7+ KB

In [ ]:
data.to_csv('/content/drive/MyDrive/DsLabMp/Data/mumbai/Flats/flats_preprocessed.csv',index=False)